

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `php` DEFAULT CHARACTER SET utf8 ;
USE `php` ;

CREATE TABLE IF NOT EXISTS `php`.`preco` (
  `idpreco` INT NOT NULL AUTO_INCREMENT,
  `preco` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idpreco`))
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `php`.`produtos` (
  `idproduto` INT NOT NULL AUTO_INCREMENT,
  `cor` VARCHAR(20) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idproduto`))
ENGINE = INNODB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
